question: >-
  Put you question here.


# Active models for this tournament
# All available models are defined in src/arbitrium/config/defaults/models.yml
# Just reference the models you want to use by their key
# You can override any setting (like temperature) if needed
models:
  gpt: {}     # Use default settings from defaults/models.yml
  claude: {}  # Use default settings from defaults/models.yml
  gemini: {}  # Use default settings from defaults/models.yml
  grok: {}

# Example: Override a specific setting for a model
# gpt:
#   temperature: 0.8  # Override default temperature

# Example: Use smaller models (all defined in defaults/models.yml)
# llama3: {}
# mistral-1: {}
# phi3: {}

# All other settings (retry, features, knowledge_bank, prompts, secrets)
# are automatically loaded from src/arbitrium/config/defaults/

# You can override any default setting by specifying it here:
# features:
#   deterministic_mode: false  # Override default

outputs_dir: "."
