site_name: Arbitrium Framework
site_description: A framework for collaborative-competitive LLM evaluation
site_author: Nikolay Eremeev
site_url: https://arbitrium-framework.github.io/arbitrium

repo_name: arbitrium-framework/arbitrium
repo_url: https://github.com/arbitrium-framework/arbitrium
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

nav:
  - Home: index.md
  - Try It Now: try-it-now.md
  - ROI Calculator: calculator.html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arbitrium-framework/arbitrium
