# Ablation Benchmark Config: Claude 4.5 Sonnet Homogeneous Tournament
# Multiple instances of the same model with different roles/perspectives

models:
  claude_skeptic:
    provider: anthropic
    model_name: claude-sonnet-4-5-20250929
    display_name: "Claude 4.5 (Skeptic)"
    temperature: 1.0
    system_prompt: >
      You are a skeptical risk analyst with a focus on identifying potential problems,
      edge cases, and failure modes. Your role is to critically examine proposals and
      highlight risks, downsides, and what could go wrong. Be constructively critical
      and help the team anticipate challenges.

  claude_strategist:
    provider: anthropic
    model_name: claude-sonnet-4-5-20250929
    display_name: "Claude 4.5 (Strategist)"
    temperature: 1.0
    system_prompt: >
      You are a pragmatic business strategist focused on market dynamics, competitive
      positioning, and strategic execution. Your role is to evaluate proposals through
      the lens of business value, market fit, and long-term strategic impact. Focus on
      practical implementation and measurable outcomes.

  claude_architect:
    provider: anthropic
    model_name: claude-sonnet-4-5-20250929
    display_name: "Claude 4.5 (Architect)"
    temperature: 1.0
    system_prompt: >
      You are a systems architect who thinks in terms of scalability, technical
      feasibility, and long-term maintainability. Your role is to evaluate proposals
      from an engineering perspective, considering technical constraints, architecture
      patterns, and implementation complexity.

outputs_dir: "./benchmarks/reports/ablation"

retry:
  max_attempts: 3
  initial_delay: 1
  max_delay: 10
  exponential_base: 2

features:
  save_reports_to_disk: true
  deterministic_mode: false
  judge_model: null  # Use peer review
  knowledge_bank_model: "leader"
  llm_compression: false

prompts:
  initial: >
    Analyze the problem from multiple perspectives using evidence-based reasoning and common sense.
    Be aware of your inherent biases and actively work to counteract them.
    Don't be constrained by current trends or prevailing narratives - trends change,
    human priorities shift, and emotional reactions should not limit objective analysis.
    Identify the core dilemma and outline several distinct, well-reasoned strategies
    grounded in scientific principles and common sense. Avoid unfalsifiable claims,
    pseudoscience, and speculative nonsense. Think critically and don't hesitate to
    challenge assumptions as the question can be self-restrictive.

  feedback: >
    Provide feedback that will allow the one to improve.
    Identify the most insightful, evidence-based ideas that stand out.
    Be aware of confirmation bias and other cognitive biases when evaluating.
    Don't favor responses that merely align with popular sentiment - value independent
    thinking that challenges current trends when evidence supports it.
    Distinguish between verifiable insights and mere speculation.
    Note which elements rely on common consensus versus proven methodology.

  improvement: >
    Improve the answer using feedback, grounding it in scientific evidence and
    practical reasoning. Recognize and mitigate your own biases in the analysis.
    Don't let emotional appeals or fashionable opinions constrain rigorous thinking.
    Make the key verifiable insights the central thesis.
    Rebuild the entire argument around this main point, removing all generic claims,
    unsubstantiated speculation, and secondary details.

  evaluate: >
    You are an editor judging analytical depth, scientific rigor and common sense. How insightful
    and evidence-based is this answer? Does it rely on proven methodology and sound
    reasoning, or does it resort to speculation and unfalsifiable claims?
    Be aware that all analysis contains inherent biases - evaluate whether the answer
    acknowledges and addresses its own potential biases. Does it demonstrate intellectual
    independence by challenging prevailing trends when warranted, or does it merely
    echo popular sentiment? Be critical of both originality and factual grounding.

knowledge_bank:
  enabled: true
  similarity_threshold: 0.75
  max_insights_to_inject: 5
